name: test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build docker compose dev container
        run: docker compose up -d

      - name: Test backend build
        run: docker run --rm --network container:quizaction-backend appropriate/curl -s -4 --retry 10 --retry-connrefused http://localhost/hello
      - name: Test frontend build
        run: docker run --rm --network container:quizaction-frontend appropriate/curl -s -4 --retry 10 --retry-connrefused http://localhost:3000
